<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ua.edu.chmnu.ki.c2.courses</groupId>
    <artifactId>numeric-methods-java</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <lombok.version>1.18.48</lombok.version>
        <maven.compiler.version>3.16.0</maven.compiler.version>
        <maven.surefire.version>3.6.0</maven.surefire.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.10.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.version}</version>
                <configuration>
                    <enablePreview>${maven.compiler.enablePreview}</enablePreview>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.version}</version>
                <configuration>
                    <argLine>${maven.surefire.argLine}</argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>java-17</id>
            <activation>
                <jdk>[17,18)</jdk>
            </activation>
            <properties>
                <maven.compiler.release>17</maven.compiler.release>
                <maven.compiler.enablePreview>true</maven.compiler.enablePreview>
                <maven.surefire.argLine>--enable-preview</maven.surefire.argLine>
            </properties>
        </profile>
        <profile>
            <id>java-21-preview</id>
            <activation>
                <jdk>[21,22)</jdk>
            </activation>
            <properties>
                <maven.compiler.release>21</maven.compiler.release>
                <maven.compiler.enablePreview>true</maven.compiler.enablePreview>
                <maven.surefire.argLine>--enable-preview</maven.surefire.argLine>
            </properties>
        </profile>
        <profile>
            <id>java-24-preview</id>
            <activation>
                <jdk>[24,25)</jdk>
            </activation>
            <properties>
                <maven.compiler.release>24</maven.compiler.release>
                <maven.compiler.enablePreview>true</maven.compiler.enablePreview>
                <maven.surefire.argLine>--enable-preview</maven.surefire.argLine>
            </properties>
        </profile>
        <profile>
            <id>java-25-preview</id>
            <activation>
                <jdk>[25,26)</jdk>
            </activation>
            <properties>
                <maven.compiler.release>25</maven.compiler.release>
                <maven.compiler.enablePreview>true</maven.compiler.enablePreview>
                <maven.surefire.argLine>--enable-preview</maven.surefire.argLine>
            </properties>
        </profile>
        <profile>
            <id>java-26-preview</id>
            <activation>
                <jdk>[26,27)</jdk>
            </activation>
            <properties>
                <maven.compiler.release>26</maven.compiler.release>
                <maven.compiler.enablePreview>true</maven.compiler.enablePreview>
                <maven.surefire.argLine>--enable-preview</maven.surefire.argLine>
            </properties>
        </profile>
    </profiles>
</project>
